name: format

on:
  pull_request:
    branches: [main]
    paths: [src/**]

jobs:
  format:
    if: ${{ github.actor }} != "dependabot"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: install and run format
        run: |
          npm ci
          npm run format

      - name: commit and push
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "style: the files have been formatted" --allow-empty
          git push origin ${{ github.head_ref }}
